services:
  - type: web
    name: TOGE-MD-V2
    env: node
    branch: main
    repo: https://github.com/toge012345/TOGE-MD-V2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: STATUS_VIEW_SEEN
        value: true
      - key: MODE
        value: public
      - key: AUTO_REACT
        value: false
